### ISSUE TITLE
Keycloak emails talk minutes

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-platform#10]
For example password reset emails include:
'This link will expire within 1440 minutes'

Would probably make more sense to use hours like:
probably it meant 24 hours

**Comment by iperdomo** [comment]
The email links are supposed to expire _soon_ and uses the property _Login action timeout_ to make the calculation. Someone changed this value to _1 day_ instead of the default _5 minutes_.

I reverted this change to the default value.
