### ISSUE TITLE
RSR k8s: enable request limits again and review as Google HealthCheck was breaking exiting limits 

### ISSUE THREAD

**Issue by dlebrero** [akvo/akvo-platform#104]
Google HealthCheck was breaking exiting request limits in the Nginx configuration, so we removed the configuration from the RSR K8s Nginx configuration (see https://github.com/akvo/akvo-rsr/blob/issue/3337-dockerize-django/nginx/default.conf)

Enable the limits and check that the Google HC still works.

**Comment by orifito** [comment]
If RSR still needs rate limiting, I'd say the way to go is an nginx ingress with [annotations](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#rate-limiting).

**Comment by dlebrero** [comment]
The git logs suggest that the rate limiting was added a year ago, so not that long ago. Can you please find out if RSR still needs rate limiting or if it is not required anymore?

**Comment by orifito** [comment]
Actually last week there were new requirements with regard to rate limiting on login/logout-related urls. I'll work on adding those rules into the nginx container.

**Comment by orifito** [comment]
Rate limiting was added to rsr nginx container
