### ISSUE TITLE
RSR k8s: Backup media files

### ISSUE THREAD

**Issue by dlebrero** [akvo/akvo-platform#105]
We need to backup the media files in the RSR persistent volume to protect us from a human doing some kind of "rm -rf".

A couple of possible k8s options: [this](https://blog.jetstack.io/blog/volume-snapshotting/) or [this](https://github.com/miracle2k/k8s-snapshots)

**Comment by dlebrero** [comment]
Do we need to run the cron job both in prod and test? It seems that the cronjobs does a snapshot of all disk in the Google project, not just the ones in the kubernetes cluster, which means that we are doing the snapshot twice a day, at the same time, which causes the snapshots to be duplicated:

![screen shot 2018-09-24 at 12 27 13](https://user-images.githubusercontent.com/2147539/45947605-357bd200-bff5-11e8-9b69-9eaf5fe7f679.png)

Note that on the 19 Sep 2018 the second snapshot has size 0 as it was triggered a couple of minutes after the other cronjob finished.

**Comment by orifito** [comment]
Ouch! cronjob removed from test environment
