### ISSUE TITLE
Communicate which login instance used when setting up two-factor authentication

### ISSUE THREAD

**Issue by bjelkeman** [akvo/akvo-platform#15]
# Context

When setting up two-factor authentication (2FA) with Keycloak you are presented with a QR code which your 2FA app can read via the camera on your phone. This saves you from having to type in a lot of data. 

# Problem or idea

The current Akvo Keycloak installations only send "user name" and "Akvo" as identification/meta-data about the 2FA installation you are setting up. In the Google 2FA app Authenticator this shows up as 

> Akvo
> NNN NNN (2FA code)
> username@domain.org

If you have multiple Keycloak instances, like login.akvo.org and login.akvotest.org then it is not obvious which one you are seeing in your 2FA app interface.

# Solution or next step

For the testing Keycloak instance, make the Akvo label something like "Akvo-test"

**Comment by iperdomo** [comment]
One way of dealing with this is to name the realms different: __akvo__ for login.akvo.org and __akvo-test__ for login.akvotest.org. The realm name is the one that shows up in the Authenticator App.

@kardan @jonase thoughts?

**Comment by kardan** [comment]
Sounds good to me. I do however have an account in the master realm so for me the label is "master" and not "akvo", but that might be fine.
