### ISSUE TITLE
Consent page to use Google for login with OAUTH

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-platform#155]
# Context
We have decided to move to Auth0 to handle user authentication for Flow and Lumen. Users will be able to login using Google email accounts (where Auth0 acts as a proxy) or any email of their preference. 

With this change, we need to create a way for users to agree to access Flow and Lumen using Google accounts. This is a common workflow when logging in to a product using any social login. 

## Why do we add this issue 
We want to make sure that the Auth0 change is:

* as smooth as possible in terms of as least possible obstruction to existing users as we can make with sufficient communication
* unifies Flow and Lumen a bit more in terms of user accounts, look and feel and workflows
* we do not remove the important features out of the blue
* we keep the changes as simple and minimal as possible to be able to improve the UX in later iterations

# Solution & next steps

Right now on Lumen test you can try out how logging in works: https://lumen.akvotest.org/library?auth=auth0

Once you select to log in with Google, you are brought to the page below. There you select the account if you have more than one and confirm you agree with Google sharing with us details like your user name and email.

![Screen Shot 2019-07-23 at 15 13 17](https://user-images.githubusercontent.com/12456965/61715184-d134b680-ad5c-11e9-9051-a1b3f7100390.png)

The idea is to brand this page too, if possible. So it is in line with the login, user access denied page, email verification pages, etc.

**Comment by tangrammer** [comment]
![Screen Shot 2019-07-23 at 15 13 17](https://user-images.githubusercontent.com/12456965/61715184-d134b680-ad5c-11e9-9051-a1b3f7100390.png)

As far as i know and could check quickly, the google account is not stylable. This window is managed by google only, and IMO doesn't have much sense  to put a different logo/style on that step from the point of view of the user, thus the user needs to know that is Google which is managing the identity at that moment

**Comment by tangrammer** [comment]
in relation to "User consent and third-party applications" with [auth0](https://auth0.com/docs/api-auth/user-consent)

in google we can distinguish 2 groups  in "[Apps with access to your account ](https://myaccount.google.com/permissions?utm_source=google-account&utm_medium=web)" 

the consent window only appears if the app that requires access belong to the first group "Third-party apps with account access"...   (If I'm not wrong  that's the current case of FLOW )

in the case of current auth0 Lumen, we only do "Signing in with Google", so there is no consent step in logging with google

**Comment by tangrammer** [comment]
Anyway the consent page of google is customizable on https://console.cloud.google.com/apis/credentials/consent?project=akvo-lumen&authuser=1&duration=P1D ... just the logo

**Comment by janagombitova** [comment]
I think if we have the logo in the page it is clear enough for the user to know they are still in the workflow to login to one of our products while making it clear that this is Google asking her for her consent, what is a very good and valid point.

**Comment by janagombitova** [comment]
* [ ] update the logo added to https://console.cloud.google.com/apis/credentials/consent?project=akvo-lumen&authuser=1&duration=P1D to match the given brand guidelines and is 120px and rounded

**Comment by janagombitova** [comment]
Received the confirmation email from Google this morning. I forwarded to you both @tangrammer and @dlebrero to check if there is more that we need to do or if this issue is ready to roll.

**Comment by janagombitova** [comment]
Works well
