### ISSUE TITLE
Handling user passwords with Auth0

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-platform#156]
# Context 
We have decided to move to Auth0 as the new login service. With this move, some of the user workflows have changed. 

With this issue we aim to make sure we are clear on how we handle passwords and the related user workflow. 

Here is the url to test things out: https://lumen.akvotest.org/library?auth=auth0

# Solution or next steps 

We need to check: 
* [x] signing up to Auth0, are we OK with the password requirements currently in place? 
* [x] check current workflow when logging in with a Google account, how does password change happen, what does the user see --> is there anything we need to change or is everything handled by Google.
* [x] check current workflow when logging in with an Auth0 account, how does password change happen, what does the user see 
* [x] check current workflow when logging in with an Auth0 account, what happens when you put in a wrong password 
* [x] when does the user receive an email (password change) and unify the email branding and copy

**Comment by janagombitova** [comment]
@Kiarii I have researched a bit how password change works and wanted to ask for your feedback on the points below. 

# Password requirements 
![Screen Shot 2019-07-29 at 10 20 49](https://user-images.githubusercontent.com/12456965/62032697-9e6e4080-b1ea-11e9-9ba3-723add43e9f0.png)
See above the current requirements. I think they are ok. Kiarii? 

# Password change with Google 
All is handled by Google, so we do **not** need to do anything in this regard. 

# Password change with Auth0 account 
The current Auth0 workflow is the following: 
1. At login click that you forgot your password 
2. Add your email 
3. Receive an email with password reset URL
4. Set up a new email
5. Confirmation screen 

Overall the workflow works well. One change that I would suggest is that the confirmation screen brings you back to the Lumen tenant you are trying to log in to, if possible. We do however need to brand these screens and the email. Kiarii?

![Screen Shot 2019-07-29 at 10 27 53](https://user-images.githubusercontent.com/12456965/62033488-5bad6800-b1ec-11e9-80e3-bb359a3dedd7.png)
![Screen Shot 2019-07-29 at 10 28 19](https://user-images.githubusercontent.com/12456965/62033558-8992ac80-b1ec-11e9-8056-b9b413424fc5.png)
![Screen Shot 2019-07-29 at 10 29 01](https://user-images.githubusercontent.com/12456965/62033564-8d263380-b1ec-11e9-9b82-69b9373ec0bf.png)
![Screen Shot 2019-07-29 at 10 29 16](https://user-images.githubusercontent.com/12456965/62033588-97e0c880-b1ec-11e9-9415-f791f41e52b2.png)
![Screen Shot 2019-07-29 at 10 29 29](https://user-images.githubusercontent.com/12456965/62033602-9fa06d00-b1ec-11e9-81b9-4738defbdcd5.png)
![Screen Shot 2019-07-29 at 10 29 56](https://user-images.githubusercontent.com/12456965/62033611-a202c700-b1ec-11e9-929e-a039099b9ed6.png)

# Inputting a wrong password 
![Screen Shot 2019-07-29 at 10 36 44](https://user-images.githubusercontent.com/12456965/62033685-c8c0fd80-b1ec-11e9-83f4-dd8347ce2b96.png)
Auth0 gives you a red warning banner. How will this look in the proposed new login screen, Kiarii?

**Comment by Kiarii** [comment]
@janagombitova I had included the pwd reset workflow in the [wireframe mockups](https://invis.io/HPT684SSABV#/375439063_0-_A0_-_Lander), of course we need to pay attention to the text content and also the pwd-reset-email-sent screen.. The pwd requirement is sth that I am going to look into, how to show that gracefully..

**Comment by janagombitova** [comment]
An update from @loicsans from this morning: I’ve added the akvo logo to the emails template, which seems to have very standard text. 

Next step is to test out the entire workflow and follow up on the remaining steps.

**Comment by janagombitova** [comment]
Updating the password and all related emails works fine. I have one tiny question: Right now once I hit to reset the password I have a tab open with the log in option and green banner that I send a request to reset my password. After receiving the email, I reset my password and get the confirmation in a separate tab. Now I need to go back to the 1st tab. This is not a problem. But is it possible for us to also bring the user to the log in page from the screen that confirms my password reset? @tangrammer and @loicsans 

![Screen Shot 2019-08-29 at 15 05 05](https://user-images.githubusercontent.com/12456965/63942952-fe1c6d80-ca6e-11e9-8ea7-5ed6e2406599.png)

**Comment by janagombitova** [comment]
Based on the decision here: #154 I suggest we keep the implementation simple and not make any further changes for now. Closing this issue.
