### ISSUE TITLE
Configure email provider in auth0

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-platform#165]
Using auth0 we need to configure an email provider, only in the trial mode we are allowed to send emails using default auth0 email provider.
Also we need to specify an email provider to customize the email templates (auth0 requisite)

**Comment by tangrammer** [comment]
so far, we are using a free sendgrid account https://akvo.slack.com/archives/C1P56H3NW/p1567149296031700?thread_ts=1567149238.030800&cid=C1P56H3NW just for testing the email template options

**Comment by dlebrero** [comment]
We opted for our own STMP server
