### ISSUE TITLE
OIDC client, how many do we really need?

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-platform#166]
Each OIDC has a main property  `application-type` that enables/disables the relates ones 

Also OIDC has specific values as `audience`, `encription-type`, `advanced-meta-data`, `redirection-urls`

Depending of our app and auth needs we should need more OIDCs, e.g: Working with configuration of email templates, we only can use the first url_redirection that we specify in the `redirection-urls` OIDC attribute

**Comment by dlebrero** [comment]
Can we close this?

**Comment by tangrammer** [comment]
yep!
