### ISSUE TITLE
Auth0 dev env

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-platform#167]
So, auth0 doesn't come with a "proper" local development option as we were used to have with keycloak.
https://auth0.com/docs/dev-lifecycle

**Comment by tangrammer** [comment]
after talking with @dlebrero about lumen issue with lumen e2e cypress tests, he mentioned that we should strive towards OpenID protocol, on both sides (client and backend).

Then we should be able to use any compliance OpenId system on any side/env

**Comment by tangrammer** [comment]
@dlebrero could we close it?
lumen side is working fine with odic-js in client side and `keycloak` so we could keep `keycloak` on `dev` env

**Comment by dlebrero** [comment]
And Flow?

**Comment by dlebrero** [comment]
We will make the decision regarding Flow when the feature flag in Flow is removed
