### ISSUE TITLE
Add links to our Terms of service and Privacy Policy to Auth0 login/signup page

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-platform#169]
When logging in/signing up to Auth0 by default we show a text that stats that by loggin in/signing up you agree to our policies. This is perfect. 

![Screen Shot 2019-09-02 at 10.41.52.png](https://images.zenhubusercontent.com/5c8f6c3ea7f08c1a3af97cc1/699ddbf0-1443-4950-9ff3-5a317abc469e)

With this issue we want to check if it is possible to add links to our policies in this page and if yes, do so. 

To keep things simple the url should point to this page: https://akvo.org/policies/

**Comment by loicsans** [comment]
It is currently not possible to add a link there.

**Comment by janagombitova** [comment]
Ok. Closing issue
