### ISSUE TITLE
Keycloak as authorization service

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-platform#171]
Relates #152
## Is Keycloak going to be able to handle the load?

Relates & https://github.com/akvo/akvo-lumen/issues/2309 & https://github.com/akvo/akvo-lumen/pull/2313

https://metrics.akvo.org/d/JjWR7wpZz/calls-to-auth-allowed-paths-copy?from=now-2d&to=now

https://github.com/akvo/akvo-lumen/blob/b4a7054635e9a35911eebcc48d69deeebfb67450/backend/resources/akvo/lumen/config.edn#L33

**Comment by kardan** [comment]
Related: https://github.com/akvo/akvo-lumen/issues/2307

**Comment by tangrammer** [comment]
Should we start monitoring the authorization calls to check the performance as we did with flow-api/check-permissions background calls?

**Comment by dlebrero** [comment]
We should always have monitoring.

That said, note that what I am personally worried about is if we are going to kill Keycloak with the new load, which would mean that we should have some confidence that we are not going to kill the production Keycloak before enabling this feature.

**Comment by tangrammer** [comment]
increased LUMEN_API_AUTHZ_PROBABILITY to 0.2

**Comment by tangrammer** [comment]
increased to 0.4 on 30th September

**Comment by tangrammer** [comment]
changed `LUMEN_API_AUTHZ_PROBABILITY`  to 0.7

**Comment by tangrammer** [comment]
changed to 1

**Comment by dlebrero** [comment]
Can we close this?
