### ISSUE TITLE
Link accounts in auth0

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-platform#181]
Relates #152 

> We need to evaluate how amount of work requires to use auth0 [linking accounts](https://auth0.com/docs/link-accounts#advantages-of-linking-accounts) before or after the auth0-akvo first release

## auht0 research
https://gist.github.com/tangrammer/890dcb52027717e2231bbf1796c12b47

## Assumptions/Premises
- "Linking accounts" is thought to collect user data from different profile connections 
- Flow and Lumen doesn't keep many user data. Lumen only first name, last name and email (before we also kept user locale). Flow only email and username 
- [x]  TODO: some experienced flow dev should confirm flow user data requirements
- In lumen side, current authz-service (doing it by keycloak) is storing user profile data, so somehow is acting as user-service too

## Steps to accomplish the work
1. we need to select the primary identity of each user, work depends on the chosen [scenario](https://gist.github.com/tangrammer/890dcb52027717e2231bbf1796c12b47#scenarios) 
2. our user-service should write some kind to read the user [linked-profile](https://gist.github.com/tangrammer/890dcb52027717e2231bbf1796c12b47#example-linked-profile) 

## Conclusions: So, how many work should we need to translate our current user data to auth0-linking-profiles service? 
1. for step one, given the small user collected data and the automatic options offered by auth0, should be easy
2. should be easy and simple using a data-oriented language such as Clojure is 😄

**Comment by dlebrero** [comment]
I don't see the answer to the questions:

1. Do we **need** to do linked accounts now or can we leave it for next year?
2. If we can leave it for later, is it going to be more work than doing it now,  or is it going to be the same?

**Comment by tangrammer** [comment]
@dlebrero 
the missed answers ... 
1. we can leave it for the next year
2. IMO, the work should be similar (if we agree in previous https://github.com/akvo/akvo-platform/issues/181#issue-498331893 )

**Comment by dlebrero** [comment]
I think we agree that we do not need to the any "user-service" yet. 

Thanks a lot for looking into this.
