### ISSUE TITLE
Review risk of Flow-API users connecting to Auth0

### ISSUE THREAD

**Issue by dlebrero** [akvo/akvo-platform#199]
As we move all users of the flow-api to Auth0, it means that the partners will be connecting directly to Auth0 to obtain an jwt token. 

As the interaction of our partners with Auth0 will be out of our control, it creates the risk of one of our partners misusing the Auth0 api's and affecting the whole of Akvo.

Review current flow-api related Keycloak usage, if similar usage will cause any issues in Auth0 and see if there is a way of mitigating the possible future Auth0 risk.

**Comment by tangrammer** [comment]
@iperdomo  found a way to not spend auth0 resources in machine-to-machine logins using token authentication method to `None`
<img width="658" alt="Screenshot 2019-12-31 at 10 26 37" src="https://user-images.githubusercontent.com/731829/71616752-1e447080-2bb8-11ea-953b-61c35ca314cb.png">

Pay attention to machine to machine consumption
<img width="326" alt="Screenshot 2019-12-31 at 09 57 15" src="https://user-images.githubusercontent.com/731829/71616287-c573d880-2bb5-11ea-9185-555f675a9622.png">
