### ISSUE TITLE
Delete the `SurveyalValue` entities from the datastore

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-platform#204]
@muloem commented on [Thu Nov 28 2019](https://github.com/akvo/akvo-flow/issues/3330)

After removing the `SurveyalValue` related code (#2231), we no longer need these entites in our datastore.  We can remove them.

**Comment by iperdomo** [comment]
The full log of _Dataflow_ executions can be found on GDrive, under `5. Development Team` > `Operations` - filename: `job-status.txt`
