### ISSUE TITLE
Debug issue with level logging in GCP console

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-platform#29]
The logging level of the `keycloak-ha-mysql` container is not getting parsed correctly, e.g. `WARN` messages are parsed as `INFO`. Then is harder to filter logging messages by severity

![info-warn](https://user-images.githubusercontent.com/178474/30270463-efdd494a-96ec-11e7-9bc4-aad283ca493b.png)

**Comment by dlebrero** [comment]
https://stackoverflow.com/questions/44164730/gke-stackdriver-java-logback-logging-format

**Comment by dlebrero** [comment]
GKE Stackdriver uses a JSON format for the logging. This JSON payload has a field called "severity" for the log level.

GKE provides a fluentd sidecar that pushes to stackdriver one log message per line printed on stdout and stderr. The GKE provided fluentd will assign "info" level to anything printed on stdout and "error" to anything in stderr, no matter the format or content of the printed line.

The K8s documentation on [Configuring Stackdriver Logging Agents](https://kubernetes.io/docs/tasks/debug-application-cluster/logging-stackdriver/#configuring-stackdriver-logging-agents) explains how to change fluentd configuration to parse the printed lines as expected, but unfortunately this means that we no longer can use the GKE provided sidecar and we will need to maintain our own.

So the options that we have right now are:

1. Log to stdout with StackDriver json format, as per StackOverflow question above. This means changing the logging config of KeyCloak plus adding the new logger to the classpath.
2. Change the fluentd configuration, and support ourselves the sidecar.

Neither of them fills me with joy.

**Comment by dlebrero** [comment]
See also https://googlecloudplatform.github.io/google-cloud-java/0.26.0/apidocs/com/google/cloud/logging/logback/LoggingAppender.html

**Comment by dlebrero** [comment]
Closing as we are not going to look into this anytime soon
